volumes:
  pg_data:
  static:
  media:

services:
  db:
    container_name: foodgram-db
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  backend:
    container_name: foodgram-back
    image: shpindik/foodgram_backend
    env_file: .env
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - db
    restart: always

  frontend:
    container_name: foodgram-front
    image: shpindik/foodgram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  gateway:
    container_name: foodgram-gateway
    depends_on:
      - db
      - backend
      - frontend
    image: shpindik/foodgram_gateway
    volumes:
      - static:/staticfiles
      - media:/media
    ports: 
      - 8001:80
